IF @Action = 'ADD'
BEGIN
    INSERT INTO TEPDEmployeeCareerHistory
    (
        CareerHistoryNo,
        EmployeeID,
        EmployeeNo,
        CompanyCode,
        EmploymentTypeCode,
        ChangeType,
        PositionCode,
        OrgStructureId,
        JobLevelCode,
        JobClassCode,
        GradeCode,
        RankCode,
        CostCenterCode,
        StartDate,
        EndDate,
        Remark,
        IsDeleted,
        WorkLocationCode,
        ResignTypeCode,
        TerminationTypeCode,
        PensionTypeCode,
        AssignmentLocation,
        EffectiveDateTo,
        TaxLocationID,
        IsIncludeSalary,
        EmpSalCompId,
        MutationTypeCode,
        UsePayrollData,
        UseOldJoinDate,
        JoinDate,
        OldEmployeeId,
        [Path],
        JabatanId,
        IsEligibleRehire,
        InsertedBy,
        InsertedDate
    )
    VALUES
    (
        @CareerHistoryNo,
        @EmployeeId,
        @EmployeeNo,
        @CompanyCode,
        @EmploymentTypeCode,
        @ChangeType,
        @PositionCode,
        @OrgStructureId,
        @JobLevelCode,
        @JobClassCode,
        @GradeCode,
        @RankCode,
        @CostCenterCode,
        @StartDate,
        @EndDate,
        @Remark,
        0,
        @WorkLocationCode,
        @ResignTypeCode,
        @TerminationTypeCode,
        @PensionTypeCode,
        @AssignmentLocation,
        @EffectiveDateTo,
        @TaxLocationId,
        @IsIncludeSalary,
        @EmpSalCompId,
        @MutationTypeCode,
        @UsePayrollData,
        @UseOldJoinDate,
        @JoinDate,
        @OldEmployeeId,
        @Path,
        @JabatanId,
        @IsEligibleRehire,
        @User,
        GETDATE()
    );
END
ELSE IF @Action = 'EDIT'
BEGIN
    UPDATE TEPDEmployeeCareerHistory
    SET
        EmployeeNo = @EmployeeNo,
        CompanyCode = @CompanyCode,
        EmploymentTypeCode = @EmploymentTypeCode,
        ChangeType = @ChangeType,
        PositionCode = @PositionCode,
        OrgStructureId = @OrgStructureId,
        JobLevelCode = @JobLevelCode,
        JobClassCode = @JobClassCode,
        GradeCode = @GradeCode,
        RankCode = @RankCode,
        CostCenterCode = @CostCenterCode,
        StartDate = @StartDate,
        EndDate = @EndDate,
        Remark = @Remark,
        WorkLocationCode = @WorkLocationCode,
        ResignTypeCode = @ResignTypeCode,
        TerminationTypeCode = @TerminationTypeCode,
        PensionTypeCode = @PensionTypeCode,
        AssignmentLocation = @AssignmentLocation,
        EffectiveDateTo = @EffectiveDateTo,
        TaxLocationID = @TaxLocationId,
        IsIncludeSalary = @IsIncludeSalary,
        EmpSalCompId = @EmpSalCompId,
        MutationTypeCode = @MutationTypeCode,
        UsePayrollData = @UsePayrollData,
        UseOldJoinDate = @UseOldJoinDate,
        JoinDate = @JoinDate,
        OldEmployeeId = @OldEmployeeId,
        Path = @Path,
        JabatanId = @JabatanId,
        IsEligibleRehire = @IsEligibleRehire,
        ModifiedBy = @User,
        ModifiedDate = GETDATE()
    WHERE CareerHistoryNo = @CareerHistoryNo;
END

