<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ThePatho.Infrastructure\ThePatho.Infrastructure.csproj" />
    <ProjectReference Include="..\ThePatho.Provider\ThePatho.Provider.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Global\Announcement\DTO\" />
    <Folder Include="Global\Announcement\Service\" />
    <Folder Include="Global\Announcement\Sql\" />
    <Folder Include="Global\BloodType\DTO\" />
    <Folder Include="Global\BloodType\Service\" />
    <Folder Include="Global\BranchBank\DTO\" />
    <Folder Include="Global\BranchBank\Service\" />
    <Folder Include="Global\Building\DTO\" />
    <Folder Include="Global\Building\Service\" />
    <Folder Include="Global\Building\Sql\" />
    <Folder Include="Global\City\DTO\" />
    <Folder Include="Global\City\Service\" />
    <Folder Include="Global\City\Sql\" />
    <Folder Include="Global\ClothSize\DTO\" />
    <Folder Include="Global\ClothSize\Service\" />
    <Folder Include="Global\ClothSize\Sql\" />
    <Folder Include="Global\Country\DTO\" />
    <Folder Include="Global\Country\Service\" />
    <Folder Include="Global\Country\Sql\" />
    <Folder Include="Global\Currency\Commands\" />
    <Folder Include="Global\Currency\DTO\" />
    <Folder Include="Global\Currency\Service\" />
    <Folder Include="Global\Currency\Sql\" />
    <Folder Include="Global\GraduationType\Commands\" />
    <Folder Include="Global\GraduationType\DTO\" />
    <Folder Include="Global\GraduationType\Service\" />
    <Folder Include="Global\GraduationType\Sql\" />
    <Folder Include="Global\Insurance\Commands\" />
    <Folder Include="Global\Insurance\DTO\" />
    <Folder Include="Global\Insurance\Service\" />
    <Folder Include="Global\Insurance\Sql\" />
    <Folder Include="Global\InventoryCondition\Commands\" />
    <Folder Include="Global\InventoryCondition\DTO\" />
    <Folder Include="Global\InventoryCondition\Service\" />
    <Folder Include="Global\InventoryCondition\Sql\" />
    <Folder Include="Global\InventoryType\Commands\" />
    <Folder Include="Global\InventoryType\DTO\" />
    <Folder Include="Global\InventoryType\Service\" />
    <Folder Include="Global\InventoryType\Sql\" />
    <Folder Include="Global\LetterCategory\Commands\" />
    <Folder Include="Global\LetterCategory\DTO\" />
    <Folder Include="Global\LetterCategory\Service\" />
    <Folder Include="Global\LetterCategory\Sql\" />
    <Folder Include="Global\LetterTemplate\Commands\" />
    <Folder Include="Global\LetterTemplate\DTO\" />
    <Folder Include="Global\LetterTemplate\Service\" />
    <Folder Include="Global\LetterTemplate\Sql\" />
    <Folder Include="Global\MaritalStatus\Commands\" />
    <Folder Include="Global\MaritalStatus\DTO\" />
    <Folder Include="Global\MaritalStatus\Service\" />
    <Folder Include="Global\MaritalStatus\Sql\" />
    <Folder Include="Global\MedicalGroup\Commands\" />
    <Folder Include="Global\MedicalGroup\DTO\" />
    <Folder Include="Global\MedicalGroup\Service\" />
    <Folder Include="Global\MedicalGroup\Sql\" />
    <Folder Include="Global\Nationality\Commands\" />
    <Folder Include="Global\Nationality\DTO\" />
    <Folder Include="Global\Nationality\Service\" />
    <Folder Include="Global\Nationality\Sql\" />
    <Folder Include="Global\NumericalSize\Commands\" />
    <Folder Include="Global\NumericalSize\DTO\" />
    <Folder Include="Global\NumericalSize\Service\" />
    <Folder Include="Global\NumericalSize\Sql\" />
    <Folder Include="Global\Province\Commands\" />
    <Folder Include="Global\Province\DTO\" />
    <Folder Include="Global\Province\Service\" />
    <Folder Include="Global\Province\Sql\" />
    <Folder Include="Global\PunishmentType\Commands\" />
    <Folder Include="Global\PunishmentType\DTO\" />
    <Folder Include="Global\PunishmentType\Service\" />
    <Folder Include="Global\PunishmentType\Sql\" />
    <Folder Include="Global\Religion\Commands\" />
    <Folder Include="Global\Religion\DTO\" />
    <Folder Include="Global\Religion\Service\" />
    <Folder Include="Global\Religion\Sql\" />
    <Folder Include="Global\ResignReason\Commands\" />
    <Folder Include="Global\ResignReason\DTO\" />
    <Folder Include="Global\ResignReason\Service\" />
    <Folder Include="Global\ResignReason\Sql\" />
    <Folder Include="Global\RewardType\Commands\" />
    <Folder Include="Global\RewardType\DTO\" />
    <Folder Include="Global\RewardType\Service\" />
    <Folder Include="Global\RewardType\Sql\" />
    <Folder Include="Global\RomanianSize\Commands\" />
    <Folder Include="Global\RomanianSize\DTO\" />
    <Folder Include="Global\RomanianSize\Service\" />
    <Folder Include="Global\RomanianSize\Sql\" />
    <Folder Include="Global\Room\Commands\" />
    <Folder Include="Global\Room\DTO\" />
    <Folder Include="Global\Room\Service\" />
    <Folder Include="Global\Room\Sql\" />
    <Folder Include="Global\ShoeSize\Commands\" />
    <Folder Include="Global\ShoeSize\DTO\" />
    <Folder Include="Global\ShoeSize\Service\" />
    <Folder Include="Global\ShoeSize\Sql\" />
    <Folder Include="Global\SkillProficiency\Commands\" />
    <Folder Include="Global\SkillProficiency\DTO\" />
    <Folder Include="Global\SkillProficiency\Service\" />
    <Folder Include="Global\SkillProficiency\Sql\" />
    <Folder Include="Global\Skill\Commands\" />
    <Folder Include="Global\Skill\DTO\" />
    <Folder Include="Global\Skill\Service\" />
    <Folder Include="Global\Skill\Sql\" />
    <Folder Include="Global\TemplateKeyword\Commands\" />
    <Folder Include="Global\TemplateKeyword\DTO\" />
    <Folder Include="Global\TemplateKeyword\Service\" />
    <Folder Include="Global\TemplateKeyword\Sql\" />
    <Folder Include="Organization\CompanyBank\DTO\" />
    <Folder Include="Organization\CompanyBank\Service\" />
    <Folder Include="Organization\CompanyBank\Sql\" />
    <Folder Include="Organization\CompanyProfile\Commands\" />
    <Folder Include="Organization\CompanyProfile\DTO\" />
    <Folder Include="Organization\CompanyProfile\Service\" />
    <Folder Include="Organization\CompanyProfile\Sql\" />
    <Folder Include="Organization\EmploymentType\Commands\" />
    <Folder Include="Organization\EmploymentType\DTO\" />
    <Folder Include="Organization\EmploymentType\Service\" />
    <Folder Include="Organization\EmploymentType\Sql\" />
    <Folder Include="Organization\Grade\Commands\" />
    <Folder Include="Organization\Grade\DTO\" />
    <Folder Include="Organization\Grade\Service\" />
    <Folder Include="Organization\Grade\Sql\" />
    <Folder Include="Organization\HistOrgStructure\Commands\" />
    <Folder Include="Organization\HistOrgStructure\DTO\" />
    <Folder Include="Organization\HistOrgStructure\Service\" />
    <Folder Include="Organization\HistOrgStructure\Sql\" />
    <Folder Include="Organization\Jabatan\Commands\" />
    <Folder Include="Organization\Jabatan\DTO\" />
    <Folder Include="Organization\Jabatan\Service\" />
    <Folder Include="Organization\Jabatan\Sql\" />
    <Folder Include="Organization\JobClass\Commands\" />
    <Folder Include="Organization\JobClass\DTO\" />
    <Folder Include="Organization\JobClass\Service\" />
    <Folder Include="Organization\JobClass\Sql\" />
    <Folder Include="Organization\JobLevelJobClass\Commands\" />
    <Folder Include="Organization\JobLevelJobClass\DTO\" />
    <Folder Include="Organization\JobLevelJobClass\Service\" />
    <Folder Include="Organization\JobLevelJobClass\Sql\" />
    <Folder Include="Organization\MutationType\Commands\" />
    <Folder Include="Organization\MutationType\DTO\" />
    <Folder Include="Organization\MutationType\Service\" />
    <Folder Include="Organization\MutationType\Sql\" />
    <Folder Include="Organization\PensionType\Commands\" />
    <Folder Include="Organization\PensionType\DTO\" />
    <Folder Include="Organization\PensionType\Service\" />
    <Folder Include="Organization\PensionType\Sql\" />
    <Folder Include="Organization\Rank\Commands\" />
    <Folder Include="Organization\Rank\DTO\" />
    <Folder Include="Organization\Rank\Service\" />
    <Folder Include="Organization\Rank\Sql\" />
    <Folder Include="Organization\ResignType\Commands\" />
    <Folder Include="Organization\ResignType\DTO\" />
    <Folder Include="Organization\ResignType\Service\" />
    <Folder Include="Organization\ResignType\Sql\" />
    <Folder Include="Organization\TerminationType\Commands\" />
    <Folder Include="Organization\TerminationType\DTO\" />
    <Folder Include="Organization\TerminationType\Service\" />
    <Folder Include="Organization\TerminationType\Sql\" />
    <Folder Include="Organization\WorkLocationGroup\Commands\" />
    <Folder Include="Organization\WorkLocationGroup\DTO\" />
    <Folder Include="Organization\WorkLocationGroup\Service\" />
    <Folder Include="Organization\WorkLocationGroup\Sql\" />
    <Folder Include="Organization\WorkLocation\Commands\" />
    <Folder Include="Organization\WorkLocation\DTO\" />
    <Folder Include="Organization\WorkLocation\Service\" />
    <Folder Include="Organization\WorkLocation\Sql\" />
    <Folder Include="PersonalInformation\EmployeePickUp\Sql\" />
    <Folder Include="PersonalInformation\Employee\Sql\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="MediatR" Version="12.4.1" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="5.0.17" />
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="SqlKata" Version="2.4.0" />
    <PackageReference Include="SqlKata.Execution" Version="2.4.0" />
  </ItemGroup>

</Project>
